Delete styling. Use jamie's external style sheet
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'approved' in 'where clause' (Connection: mysql, SQL: select * from `patients` where `approved` = 0).

Need to select from users table for `approved`